---
##############################################
##                                          ##
##       Installing The Jenkins             ##
##                                          ##
##############################################

- name: Instal jenkins
  hosts: jenkins
  become: true

# Prerequisites

  tasks:
  - name: apt-get update
    apt:
      update_cache: yes

  - name: install Requirements
    apt:
      pkg:
      - autoconf
      - automake
      - gcc
      - libc6
      - libmcrypt-dev
      - libssl-dev
      - make
      - wget
      - bc
      - dc
      - gawk
      - build-essential
      - snmp
      - libnet-snmp-perl
      - gettext
      - openssl
      - python3
      - python3-apt
      state: present

# sudo apt-get install -y autoconf gcc libc6 libmcrypt-dev make libssl-dev wget bc gawk dc build-essential snmp libnet-snmp-perl gettext


#  Downloading The Source
  - name: download sources nrpe-4.1.0.tar.gz
    unarchive: 
      src: https://github.com/NagiosEnterprises/nrpe/archive/nrpe-4.1.0.tar.gz
      dest: /tmp/
      remote_src: yes

#  -name: unzip nrpe-4.1.0.tar.gz

#cd /tmp
#wget --no-check-certificate -O nrpe.tar.gz https://github.com/NagiosEnterprises/nrpe/archive/nrpe-4.1.0.tar.gz
#tar xzf nrpe.tar.gz

#   Compile

  - name: Configure NRPE
    command: /tmp/nrpe-nrpe-4.1.0/configure --enable-command-args --with-ssl-lib=/usr/lib/x86_64-linux-gnu/
    args:
      chdir: /tmp/nrpe-nrpe-4.1.0/

    

#cd /tmp/nrpe-nrpe-4.1.0/
#sudo ./configure --enable-command-args --with-ssl-lib=/usr/lib/x86_64-linux-gnu/
#sudo make all

  - name: Compile NRPE
    command: "{{ item }}"
    args:
      chdir: /tmp/nrpe-nrpe-4.1.0/
    with_items:
      - make all
      - make install-groups-users
      - make install
      - make install-config
    

#Create User And Group

#sudo make install-groups-users


# Install Binaries

#sudo make install

# Install Configuration Files

#sudo make install-config


#--------------------------------------

# Update Services File

#sudo sh -c "echo >> /etc/services"
#sudo sh -c "sudo echo '# Nagios services' >> /etc/services"
#sudo sh -c "sudo echo 'nrpe    5666/tcp' >> /etc/services"

  - name: Update Services File
    ansible.builtin.lineinfile:
      path: /etc/services
      line: "{{ item }}"
    with_items:
      - ' '     
      - '# Nagios services'
      - 'nrpe    5666/tcp'


# Install Service / Daemon

#sudo make install-init
  - name: Install Service / Daemon
    command: make install-init
    args:
      chdir: /tmp/nrpe-nrpe-4.1.0

# sudo systemctl enable nrpe.service


# Configure Firewall


#sudo mkdir -p /etc/ufw/applications.d

  - name: Create a directory /etc/ufw/applications.d
    ansible.builtin.file:
      path: /etc/ufw/applications.d
      state: directory
      mode: '0755'

#sudo sh -c "echo '[NRPE]' > /etc/ufw/applications.d/nagios"
#sudo sh -c "echo 'title=Nagios Remote Plugin Executor' >> /etc/ufw/applications.d/nagios"
#sudo sh -c "echo 'description=Allows remote execution of Nagios plugins' >> /etc/ufw/applications.d/nagios"
#sudo sh -c "echo 'ports=5666/tcp' >> /etc/ufw/applications.d/nagios"

 