network:
  ethernets:
    enp0s3:
      dhcp4: no
      addresses: [192.168.1.200/24]
      gateway4: 192.168.1.1
    enp0s8:
      dhcp4: no
      addresses: [10.92.12.1/24]
      gateway4: 10.92.12.1
    enp0s9:
      dhcp4: no
      addresses: [10.2.92.1/24]
      gateway4: 10.2.92.1
  version: 2